export const Directional: { [key: string]: string } = {
  north: 'N',
  northeast: 'NE',
  east: 'E',
  southeast: 'SE',
  south: 'S',
  southwest: 'SW',
  west: 'W',
  northwest: 'NW'
}

export const Street_Type: { [key: string]: string } = {
  Apartment: 'AP',
  Alley: 'AL',
  Arcade: 'ARC',
  Avenue: 'AVE',
  Bouleletd: 'BLV',
  Bend: 'BND',
  Bypass: 'BPS',
  Brace: 'BR',
  Circuit: 'CCT',
  Chase: 'CH',
  Circle: 'CIR',
  Close: 'CL',
  Common: 'CMN',
  Concourse: 'CNC',
  Corner: 'CNR',
  Circus: 'CRC',
  Crescent: 'CRS',
  Crossing: 'CSG',
  Corso: 'CSO',
  Court: 'CT',
  Centre: 'CTR',
  Cove: 'CVE',
  Causeway: 'CWY',
  Drive: 'DR',
  Driveway: 'DRY',
  Entrance: 'ENT',
  Esplanade: 'ESP',
  Expressway: 'EXP',
  Fairway: 'FAY',
  Frontage: 'FR',
  Freeway: 'FWY',
  Garden: 'GDN',
  Glade: 'GL',
  Glen: 'GLN',
  Grange: 'GRA',
  Ground: 'GRD',
  Green: 'GRN',
  Gate: 'GTE',
  Grove: 'GVE',
  Heights: 'HTS',
  Highway: 'HWY',
  Junction: 'JN',
  Key: 'KEY',
  Lane: 'LA',
  Link: 'LK',
  Loop: 'LP',
  Mall: 'ML',
  Mount: 'MT',
  Mews: 'MW',
  Motorway: 'MWY',
  Nook: 'NK',
  Outlook: 'OUT',
  Parade: 'PDE',
  Place: 'PL',
  Plaza: 'PLZ',
  Point: 'PNT',
  Promenade: 'PRM',
  Pass: 'PSS',
  Path: 'PT',
  Parkway: 'PWY',
  Quadrant: 'QD',
  Quadrangle: 'QDG',
  Quay: 'QY',
  Road: 'RD',
  Ridge: 'RDG',
  Roadway: 'RDY',
  Reserve: 'RES',
  Rise: 'RI',
  Round: 'RN',
  Row: 'ROW',
  Rest: 'RST',
  Retreat: 'RT',
  Route: 'RTE',
  'Right of Way': 'RTW',
  Siding: 'SDG',
  Square: 'SQ',
  Shop: 'SH',
  Street: 'ST',
  STS: 'ST',
  Streets: 'STS',
  Terrace: 'TCE',
  Track: 'TR',
  Trail: 'TRL',
  Tollway: 'TWY',
  View: 'VW',
  Way: 'WAY',
  Walk: 'WK',
  Walkway: 'WKY',
  Wynd: 'WND'
}

export const State_Code: { [key: string]: string } = {
  'New South Wales': 'NSW',
  'Northern Territory	': 'NT',
  Queensland: 'QLD',
  'South Australia': 'SA',
  Tasmania: 'TAS',
  Victoria: 'VIC',
  'Western Australia': 'WA'
}
